#!/bin/bash
# Start Qwen3-Embedding-4B service for stage3 vector index building
set -euo pipefail

EMBEDDING_MODEL_NAME="${EMBEDDING_MODEL_NAME:-Qwen/Qwen3-Embedding-4B}"
EMBEDDING_SERVED_MODEL_NAME="${EMBEDDING_SERVED_MODEL_NAME:-$EMBEDDING_MODEL_NAME}"
EMBEDDING_HOST="${EMBEDDING_HOST:-0.0.0.0}"
EMBEDDING_PORT="${EMBEDDING_PORT:-11810}"
EMBEDDING_TENSOR_PARALLEL_SIZE="${EMBEDDING_TENSOR_PARALLEL_SIZE:-1}"
EMBEDDING_GPU_MEMORY_UTILIZATION="${EMBEDDING_GPU_MEMORY_UTILIZATION:-0.9}"
CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}" \
vllm serve "$EMBEDDING_MODEL_NAME" \
--served-model-name "$EMBEDDING_SERVED_MODEL_NAME" \
--host "$EMBEDDING_HOST" \
--port "$EMBEDDING_PORT" \
--tensor-parallel-size "$EMBEDDING_TENSOR_PARALLEL_SIZE" \
--gpu-memory-utilization "$EMBEDDING_GPU_MEMORY_UTILIZATION" \
--task embed
