#!/bin/bash
# Start Qwen3-Reranker-4B service for stage4 retrieval reranking
set -euo pipefail

RERANKER_MODEL_NAME="${RERANKER_MODEL_NAME:-Qwen/Qwen3-Reranker-4B}"
RERANKER_SERVED_MODEL_NAME="${RERANKER_SERVED_MODEL_NAME:-$RERANKER_MODEL_NAME}"
RERANKER_HOST="${RERANKER_HOST:-0.0.0.0}"
RERANKER_PORT="${RERANKER_PORT:-12810}"
RERANKER_TENSOR_PARALLEL_SIZE="${RERANKER_TENSOR_PARALLEL_SIZE:-1}"
RERANKER_GPU_MEMORY_UTILIZATION="${RERANKER_GPU_MEMORY_UTILIZATION:-0.9}"
CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}" \
vllm serve "$RERANKER_MODEL_NAME" \
--served-model-name "$RERANKER_SERVED_MODEL_NAME" \
--host "$RERANKER_HOST" \
--port "$RERANKER_PORT" \
--tensor-parallel-size "$RERANKER_TENSOR_PARALLEL_SIZE" \
--gpu-memory-utilization "$RERANKER_GPU_MEMORY_UTILIZATION"
